config/routes.rb
CruiseControl::Application.routes.draw do
  match '/' => 'projects#index'
  
  resources :projects do  
    member do
      post :build
      get :getting_started
    end
  end

  match 'builds/older/:project' => 'builds#drop_down', :as => :builds_drop_down
  match 'builds/:project/:build/*path' => 'builds#artifact', :as => :build_artifact, :build => /[^\/]+/
  match 'builds/:project/:build' => 'builds#show', :as => :build, :build => /[^\/]+/
  match 'builds/:project' => 'builds#show', :as => :project_without_builds

  match 'projects/code/:id/*path' => 'projects#code', :as => :code

  match 'documentation/plugins' => 'documentation#plugins', :as => :plugin_doc_list
  match 'documentation/plugins/:type/:name' => 'documentation#plugins', :as => :plugin_doc, :name => /[^\/]+/

  match 'documentation/*path' => 'documentation#get', :as => :document
  match 'documentation' => 'documentation#get', :as => :document_root
  
  match 'XmlStatusReport.aspx' => 'projects#index', :format => 'cctray'
  match 'XmlServerReport.aspx' => 'projects#index', :format => 'cctray'

  # TODO Remove this.
  match '/:controller(/:action(/:id))'
end

app/models/build.rb
# A Build represents a single build of a particular Project. It possesses all of the attributes
# typically associated with a CI build, such as revision, status, and changeset.
class Build
  include CommandLine
  
  class ConfigError < StandardError; end

  attr_reader :project, :label
  IGNORE_ARTIFACTS = /^(\..*|build_status\..+|build.log|changeset.log|cruise_config.rb|plugin_errors.log)$/

  def initialize(project, label, initialize_artifacts_directory=false)
    @project, @label = project, label.to_s
    @start = Time.now
    if initialize_artifacts_directory
      unless File.exist? artifacts_directory
        FileUtils.mkdir_p artifacts_directory
        clear_cache
      end
    end
  end

  def build_status
    BuildStatus.new(artifacts_directory)
  end

  def latest?
    label == project.last_build.label
  end

  def fail!(error = nil)
    build_status.fail!(seconds_since(@start), error)
  end
  
  def run
    build_log = artifact 'build.log'
    File.open(artifact('cruise_config.rb'), 'w') {|f| f << @project.config_file_content }

    begin
      raise ConfigError.new(@project.error_message) unless @project.config_valid?
      in_clean_environment_on_local_copy do
        if @project.uses_bundler?
          execute self.bundle_install, :stdout => build_log, :stderr => build_log
        end
        execute self.command, :stdout => build_log, :stderr => build_log
      end
      build_status.succeed!(seconds_since(@start))
    rescue => e
      if File.exists?(project.local_checkout + "/trunk")
        msg = <<EOF

WARNING:
Directory #{project.local_checkout}/trunk exists.
Maybe that's your APP_ROOT directory.
Try to remove this project, then re-add it with correct APP_ROOT, e.g.

rm -rf #{project.path}
./cruise add #{project.name} svn://my.svn.com/#{project.name}/trunk
EOF
        File.open(build_log, 'a'){|f| f << msg }
      end

      File.open(build_log, 'a'){|f| f << e.message }
      CruiseControl::Log.verbose? ? CruiseControl::Log.debug(e) : CruiseControl::Log.info(e.message)
      if e.is_a?(CommandLine::ExecutionError) # i.e., the build returned a non-zero status code
        fail!
      else
        fail!(e.message)
      end
    end
  end
  
  def brief_error
    return error unless error.blank?
    return "plugin error" unless plugin_errors.empty?
    nil
  end
  
  def destroy
    FileUtils.rm_rf artifacts_directory
  end
  alias abort destroy

  def additional_artifacts
    Dir.entries(artifacts_directory).find_all {|artifact| !(artifact =~ IGNORE_ARTIFACTS) }
  end
  
  def status
    build_status.to_s
  end

  def successful?
    build_status.succeeded?
  end

  def failed?
    build_status.failed?
  end

  def incomplete?
    build_status.incomplete?
  end

  def revision
    label.split(".")[0]
  end

  def changeset
    @changeset ||= contents_for_display(artifact('changeset.log'))
  end

  def output
    @output ||= contents_for_display(artifact('build.log'))
  end
  
  def project_settings
    @project_settings ||= contents_for_display(artifact('cruise_config.rb'))
  end

  def error
    @project_settings ||= contents_for_display(build_status.error_message_file)
  end

  def plugin_errors
    @plugin_errors ||= contents_for_display(artifact('plugin_errors.log'))
  end

  def time
    build_status.timestamp
  end

  def artifacts_directory
    Dir["#{@project.path}/build-#{label}*"].sort.first || File.join(@project.path, "build-#{label}")
  end
  
  def clear_cache
    FileUtils.rm_f Rails.root.join(Rails.root, 'public', 'builds', 'older', "#{@project.name}.html")
  end
  
  def url
    dashboard_url = Configuration.dashboard_url
    raise "Configuration.dashboard_url is not specified" if dashboard_url.nil? || dashboard_url.empty?
    dashboard_url + Rails.application.routes.url_helpers.build_path(:project => project, :build => to_param)
  end
  
  def artifact(path)
    File.join(artifacts_directory, path)
  end

  def contents_for_display(file)
    return '' unless File.file?(file) && File.readable?(file)
    file_size_kbytes = File.size(file) / 1024
    if file_size_kbytes < 100
      File.read(file)
    else
      contents = File.read(file, 100 * 1024)
      response = "#{file} is #{file_size_kbytes} kbytes - too big to display in the dashboard, the output is truncated\n\n\n"
      response += contents
    end
  end

  def command
    project.build_command or rake
  end
  
  def rake_task
    project.rake_task
  end

  def bundle_install
    vendor  = File.join project.local_checkout, "vendor"
    Platform.bundle_cmd + %{ check --gemfile=#{project.gemfile} } + "||" + Platform.bundle_cmd + %{ install --path=#{vendor} --gemfile=#{project.gemfile} --no-color }
  end

  def rake
    # Simply calling rake is this convoluted due to idiosyncrasies of Windows, Debian and JRuby.
    # --nosearch flag here prevents CC.rb from building itself when a project has no Rakefile.
    # ARGV.clear at the end prevents Test::Unit's AutoRunner from doing anything silly.
    cc_build_path = Rails.root.join('tasks', 'cc_build.rake')
    maybe_trace   = CruiseControl::Log.verbose? ? " << '--trace'" : ""
    
    if project.uses_bundler?
      %{BUNDLE_GEMFILE=#{project.gemfile} } + Platform.bundle_cmd + %{ exec rake -e "load '#{cc_build_path}'; ARGV << '--nosearch'#{maybe_trace} << 'cc:build'; Rake.application.run; ARGV.clear"}
    else  
      Platform.interpreter + %{ -e "require 'rubygems' rescue nil; require 'rake'; load '#{cc_build_path}'; ARGV << '--nosearch'#{maybe_trace} << 'cc:build'; Rake.application.run; ARGV.clear"}
    end
  end
  
  def in_clean_environment_on_local_copy(&block)
    old_rails_env = ENV['RAILS_ENV']

    Bundler.with_clean_env do
      begin
        ENV['RAILS_ENV'] = nil

        # set OS variable CC_BUILD_ARTIFACTS so that custom build tasks know where to redirect their products
        ENV['CC_BUILD_ARTIFACTS'] = self.artifacts_directory
        # set OS variablea CC_BUILD_LABEL & CC_BUILD_REVISION so that custom build tasks can use them
        ENV['CC_BUILD_LABEL'] = self.label
        ENV['CC_BUILD_REVISION'] = self.revision
        # CC_RAKE_TASK communicates to cc:build which task to build (if self.rake_task is not set, cc:build will try to be
        # smart about it)
        ENV['CC_RAKE_TASK'] = self.rake_task

        Dir.chdir(project.local_checkout) do
          block.call
        end
      ensure
        ENV['RAILS_ENV'] = old_rails_env
      end
    end
  end

  def to_param
    self.label
  end
  
  def elapsed_time
    build_status.elapsed_time
  end

  def elapsed_time_in_progress
    build_status.elapsed_time_in_progress
  end

  def seconds_since(start)
    (Time.now - start).ceil.abs
  end

  def abbreviated_label
    revision, rebuild_number = label.split('.')
    [revision[0..6], rebuild_number].compact.join('.')
  end

end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  caches_page :drop_down
  
  def show
    render :text => 'Project not specified', :status => 404 and return unless params[:project]
    @project = Project.find(params[:project])
    render :text => "Project #{params[:project].inspect} not found", :status => 404 and return unless @project

    if params[:build]
      @build = @project.find_build(params[:build])
      render :text => "Build #{params[:build].inspect} not found", :status => 404 and return if @build.nil? 
    else
      @build = @project.last_build
      render :action => 'no_builds_yet' and return if @build.nil?
    end

    @builds_for_navigation_list, @builds_for_dropdown = partitioned_build_lists(@project)

    @autorefresh = @build.incomplete?
  end

  def artifact
    render :text => 'Project not specified', :status => 404 and return unless params[:project]
    render :text => 'Build not specified', :status => 404 and return unless params[:build]
    render :text => 'Path not specified', :status => 404 and return unless params[:path]

    @project = Project.find(params[:project])
    render :text => "Project #{params[:project].inspect} not found", :status => 404 and return unless @project
    @build = @project.find_build(params[:build])
    render :text => "Build #{params[:build].inspect} not found", :status => 404 and return unless @build

    path = @build.artifact(params[:path])

    if File.directory? path
      if File.exists?(File.join(path, 'index.html'))
        redirect_to request.fullpath + '/index.html'
      else
        # TODO: generate an index from directory contents
        render :text => "this should be an index of #{params[:path]}"
      end
    elsif File.exists? path
      send_file(path, :type => get_mime_type(path), :disposition => 'inline', :stream => false)
    else
      render_not_found
    end
  end
  
  private

    MIME_TYPES = {
      "html" => "text/html",
      "js"   => "text/javascript",
      "css"  => "text/css",
      "gif"  => "image/gif",
      "jpg"  => "image/jpeg",
      "jpeg" => "image/jpeg",
      "png"  => "image/png",
      "zip"  => "application/zip"
    }

    def get_mime_type(name)
      extension = name.downcase.split(".").last
      return MIME_TYPES[ extension ]if MIME_TYPES.has_key? extension
      "text/plain"
    end

    def partitioned_build_lists(project)
      builds = project.builds.reverse
      partition_point = Configuration.build_history_limit

      return builds[0...partition_point], builds[partition_point..-1]
    end

end

app/helpers/builds_helper.rb
module BuildsHelper

  def select_builds(project, builds)
    return "" if builds.blank?

    options = [ [ "Older Builds...", nil ] ] + builds.map do |build|
      [ build_to_text(build, false), build_path(project.id, build.label) ]
    end
    
    select_tag "build", options_for_select(options)
  end
  
  def format_build_log(log)
    strip_ansi_colors(highlight_test_count(link_to_code(h(log))))
  end
  
  def link_to_code(log)
    return log if Configuration.disable_code_browsing
    @work_path ||= File.expand_path(@project.path + '/work')
    
    log.gsub(/(\#\{RAILS_ROOT\}\/)?([\w\.-]*\/[ \w\/\.-]+)\:(\d+)/) do |match|
      path = File.expand_path($2, @work_path)
      line = $3
      if path.index(@work_path) == 0
        path = path[@work_path.size..-1]
        link_to match, "/projects/code/#{h @project.name}#{path}?line=#{line}##{line}"
      else
        match
      end
    end
  end
  
  def format_project_settings(settings)
    settings = settings.strip
    if settings.empty?
      "This project has no custom configuration. Maybe it doesn't need it.<br/>" +
      "Otherwise, #{link_to('the manual', document_path('manual'))} can tell you how."
    else
      h(settings)
    end
  end
  
  def failures_and_errors_if_any(log)
    errors = BuildLogParser.new(log).failures_and_errors
    return nil if errors.empty?
    
    link_to_code(errors.collect{|error| format_test_error_output(error)}.join)
  end
  
  def format_test_error_output(test_error)
    message = test_error.message

    "Name: #{test_error.test_name}\n" +
    "Type: #{test_error.type}\n" +
    "Message: #{h message}\n\n" +
    "<span class=\"error\">#{h test_error.stacktrace}</span>\n\n\n"
  end

  def display_build_time
    if @build.incomplete?
      if @build.latest?
        "building for #{format_seconds(@build.elapsed_time_in_progress, :general)}"
      else
        "started at #{format_time(@build.time, :verbose)}, and never finished"
      end
    else
      elapsed_time_text = elapsed_time(@build, :precise)
      build_time_text = format_time(@build.time, :verbose)
      elapsed_time_text.empty? ? "finished at #{build_time_text}" : "finished at #{build_time_text} taking #{elapsed_time_text}"
    end
  end

  private

  def highlight_test_count(log)
    log.gsub(/\d+ tests, \d+ assertions, \d+ failures, \d+ errors/, '<div class="test-results">\0</div>').
        gsub(/\d+ examples, \d+ failures/, '<div class="test-results">\0</div>')
  end

  def strip_ansi_colors(log)
    log.gsub(/\e\[\d+m/, '')
  end
end

app/views/builds/_build_buttons.html.erb
<div class="buttons">
  <%= form_tag(build_project_path(:id => project), :class => "build_project") do %>
  
    <% if project.builder_down? %>    
      <button type="submit" name="build_now" class="build_button">Start Builder</button>
    <% elsif project.can_build_now? %>
      <button type="submit" name="build_now" class="build_button">Build Now</button>
    <% else %>
      <button type="submit" name="build_now" class="build_button" disabled="disabled">Build Now</button>
    <% end %>
    
  <% end %>
  
  <%= display_builder_state(project.builder_state_and_activity) %>
</div>

app/views/builds/no_builds_yet.html.erb
<div id="no_builds_help" class="help">
  <p><%= h @project.name %> doesn't have any builds yet.</p>
  <p>
    To start building this project, you need to start the builder. Open command line in the directory where you
    unpacked CruiseControl.rb, and type:
  </p>
  <pre style="font-family: courier, monospace">  cruise build <%= h @project.name %></pre>
</div>

app/views/builds/show.html.erb
<% @rss_feeds = {"#{@project.name} builds" => {:controller => 'projects', :action => 'show', :id => @project, :format => 'rss'}} -%>

<div id="builds_list">
  <div id="project_build_now" class="builder_control">
    <%= render :partial => "builds/build_buttons", :locals => { :project => @project } %>
  </div>
  
  <div id="navigate_build">
    <% prev_build, next_build = @project.previous_build(@build), @project.next_build(@build)%>
    
    <%= link_to "&lt; prev".html_safe, build_path(@project.name, prev_build), :accesskey => 'k' unless prev_build.nil? %>
    <strong><%= @build.abbreviated_label %></strong>
    <%= link_to "next &gt;".html_safe, build_path(@project.name, next_build), :accesskey => 'j' unless next_build.nil? %>
    <%= link_to "latest &gt;&gt;".html_safe, project_without_builds_path(@project.name) unless next_build.nil? %>
  </div>
  
  <% @builds_for_navigation_list.each do |build| %>
    <div class="build_link<%= ' selected' if @build.label == build.label %>">
      <%= link_to_build(@project, build) %>
    </div>
  <% end %>

  <div id="builds_drop_down">
    <%= select_builds(@project, @builds_for_dropdown) %>
  </div>  
</div>

<br />

<div id="build_details">
  <h1>
    <%= h @project.name %> build <%= h @build.abbreviated_label %>
    <% if @build.failed? %><span class="error">FAILED</span><% end %>
    <% if @build.incomplete? %> (INCOMPLETE)<% end %>    
  </h1>
  <div class="build_time">
    <%= display_build_time %>
  </div>

  <br/>

  <div class="section">
    <div class="section_header">Build Changeset</div>
    <div class="section_content"><%= format_changeset_log(@build.changeset) %></div>
  </div>

  <% test_failures = failures_and_errors_if_any(@build.output) %>
  <% if test_failures %>
    <div class="section">
      <div class="section_header">Test Failures and Errors</div>
      <div class="section_content"><%= test_failures %></div>
    </div>
  <% end %>

  <% plugin_errors = @build.plugin_errors %>
  <% unless plugin_errors.empty? %>
    <div class="section">
      <div class="section_header">Plugin Errors</div>
      <div class="section_content"><%= h plugin_errors %></div>
    </div>
  <% end %>

  <div class="section <%= @build.incomplete? ? '' : 'closed' %>">
    <div class="section_header">Build Log</div>
    <div class="section_content"><div class="logfile"><%= format_build_log(@build.output) %></div><div><%= link_to "See unformatted build log&hellip;".html_safe, build_artifact_path(:project => @project.name, :build => @build.label, :path => 'build.log') %></div></div>
  </div>

  <% unless @build.additional_artifacts.empty? %>
    <div class="section">
      <div class="section_header">Custom Build Artifacts</div>
      <div class="section_content"><% @build.additional_artifacts.each do |artifact| %><div class="artifact"><%= link_to artifact, build_artifact_path(:project => @project.name, :build => @build.label, :path => artifact) %></div><% end %></div>
    </div>
  <% end %>
  
  <div class="section closed">
    <div class="section_header">Project Settings</div>
    <div class="section_content"><%= format_project_settings(@build.project_settings) %></div>
  </div>


</div>