config/routes.rb
CruiseControl::Application.routes.draw do
  match '/' => 'projects#index'
  
  resources :projects do  
    member do
      post :build
      get :getting_started
    end
  end

  match 'builds/older/:project' => 'builds#drop_down', :as => :builds_drop_down
  match 'builds/:project/:build/*path' => 'builds#artifact', :as => :build_artifact, :build => /[^\/]+/
  match 'builds/:project/:build' => 'builds#show', :as => :build, :build => /[^\/]+/
  match 'builds/:project' => 'builds#show', :as => :project_without_builds

  match 'projects/code/:id/*path' => 'projects#code', :as => :code

  match 'documentation/plugins' => 'documentation#plugins', :as => :plugin_doc_list
  match 'documentation/plugins/:type/:name' => 'documentation#plugins', :as => :plugin_doc, :name => /[^\/]+/

  match 'documentation/*path' => 'documentation#get', :as => :document
  match 'documentation' => 'documentation#get', :as => :document_root
  
  match 'XmlStatusReport.aspx' => 'projects#index', :format => 'cctray'
  match 'XmlServerReport.aspx' => 'projects#index', :format => 'cctray'

  # TODO Remove this.
  match '/:controller(/:action(/:id))'
end

app/models/project.rb
# A Project represents a particular CI build of a particular codebase. An instance is created 
# each time a build is triggered and yielded back to be configured by cruise_config.rb.
class Project
  attr_reader :name, :plugins, :build_command, :rake_task, :config_tracker, :path, :settings, :config_file_content, :error_message
  attr_accessor :source_control, :scheduler, :use_bundler, :gemfile

  alias_method :id, :name
  
  class << self
    attr_accessor_with_default :plugin_names, []
    attr_accessor :current_project
    
    def all(dir=Configuration.projects_root)
      load_all(dir).map do |project_dir|
        load_project project_dir
      end
    end
    
    def create(project_name, scm, dir=Configuration.projects_root)
      Project.new(:name => project_name, :scm => scm).tap do |project|
        raise "Project named #{project.name.inspect} already exists in #{dir}" if Project.all(dir).include?(project)
        begin
          save_project(project, dir)
          checkout_local_copy(project)
          write_config_example(project)
        rescue
          FileUtils.rm_rf "#{dir}/#{project.name}"
          raise
        end
      end
    end
    
    def plugin(plugin_name)
      self.plugin_names << plugin_name unless Rails.env == 'test' or self.plugin_names.include? plugin_name
    end

    def read(dir, load_config = true)
      Project.new(:name => File.basename(dir)).tap do |project|
        self.current_project = project
        project.load_config if load_config
      end
    ensure
      self.current_project = nil
    end

    def configure
      raise 'No project is currently being created' if current_project.nil?
      yield current_project
    end
    
    def find(project_name, dir=Configuration.projects_root)
      # TODO: sanitize project_name to prevent a query injection attack here      
      path = dir.join(project_name)
      return nil unless File.directory?(path)
      load_project(path)
    end

    def load_project(dir)
      read(dir, load_config = false).tap do |project|
        project.path = dir
      end
    end
    
    private
    
      def load_all(dir)
        Dir["#{dir}/*"].find_all {|child| File.directory?(child)}.sort
      end
    
      def save_project(project, dir)
        project.path = File.join(dir, project.name)
        FileUtils.mkdir_p project.path
      end

      def checkout_local_copy(project)
        work_dir = File.join(project.path, 'work')
        FileUtils.mkdir_p work_dir
        project.source_control.checkout
      end

      def write_config_example(project)
        config_example = Rails.root.join('config', 'cruise_config.rb.example')
        config_in_subversion = File.join(project.path, 'work', 'cruise_config.rb')
        cruise_config = File.join(project.path, 'cruise_config.rb')
        if File.exists?(config_example) and not File.exists?(config_in_subversion)
          FileUtils.cp(config_example, cruise_config)
        end
      end
  end
  
  def initialize(attrs = {})
    attrs = attrs.with_indifferent_access

    @name = attrs[:name] || ""
    @path = attrs[:path] || Configuration.projects_root.join(@name)
    @scheduler = PollingScheduler.new(self)
    @plugins = []
    @config_tracker = ProjectConfigTracker.new(self.path)
    @settings = ''
    @config_file_content = ''
    @error_message = ''
    @triggers = [ ChangeInSourceControlTrigger.new(self) ]
    self.source_control = attrs[:scm] if attrs[:scm]

    instantiate_plugins
  end
  
  def source_control=(scm_adapter)
    scm_adapter.path = local_checkout
    @source_control = scm_adapter
  end

  def source_control
    @source_control || self.source_control = SourceControl.detect(local_checkout)
  end

  def load_and_remember(file)
    return unless File.file?(file)
    @settings << File.read(file) << "\n"
    @config_file_content = @settings
    load file
  end

  def load_config
    begin
      retried_after_update = false
      begin
        load_and_remember config_tracker.central_config_file
      rescue Exception 
        if retried_after_update
          raise
        else
          source_control.update
          retried_after_update = true
          retry
        end
      end
      load_and_remember config_tracker.local_config_file
    rescue Exception => e
      @error_message = "Could not load project configuration: #{e.message} in #{e.backtrace.first}"
      CruiseControl::Log.event(@error_message, :fatal) rescue nil
      @settings = ""
    end
    self
  end

  def path=(value)
    value = File.expand_path(value)
    @config_tracker = ProjectConfigTracker.new(value)
    @path = value
    @source_control.path = local_checkout if @source_control
    @path
  end

  def instantiate_plugins
    self.class.plugin_names.each do |plugin_name|
      plugin_instance = plugin_name.to_s.camelize.constantize.new(self)
      self.add_plugin(plugin_instance)
    end
  end

  def add_plugin(plugin, plugin_name = plugin.class)
    @plugins << plugin
    plugin_name = plugin_name.to_s.underscore.to_sym
    if self.respond_to?(plugin_name)
      raise "Cannot register an plugin with name #{plugin_name.inspect} " +
            "because another plugin, or a method with the same name already exists"
    end
    self.singleton_class.send(:define_method, plugin_name) { plugin }
    plugin
  end

  def ==(another)
    another.is_a?(Project) and another.name == self.name
  end
  
  def config_valid?
    @settings == @config_file_content
  end

  def build_command=(value)
    raise 'Cannot set build_command when rake_task is already defined' if value and @rake_task
    @build_command = value
  end

  def rake_task=(value)
    raise 'Cannot set rake_task when build_command is already defined' if value and @build_command
    @rake_task = value
  end

  def local_checkout
    File.join(@path, 'work')
  end

  def builds
    raise "Project #{name.inspect} has no path" unless path

    the_builds = Dir["#{path}/build-*"].collect do |build_dir|
      build_directory = File.basename(build_dir)
      build_label = build_directory.split("-")[1]
      Build.new(self, build_label)
    end

    order_by_label(the_builds)
  end

  def builder_state_and_activity
    BuilderStatus.new(self).status
  end
  
  def builder_down?
    self.builder_state_and_activity == 'builder_down'
  end
  
  def can_build_now?
    !(building? || builder_down? || Configuration.disable_build_now)
  end
  
  def building?
    self.builder_state_and_activity == 'building'
  end
  
  def builder_error_message
    BuilderStatus.new(self).error_message
  end
  
  def last_build
    builds.last
  end
  
  def create_build(label)
    Build.new(self, label, true)
  end
  
  def previous_build(current_build)  
    all_builds = builds
    index = get_build_index(all_builds, current_build.label)
    
    if index > 0
      return all_builds[index-1]
    else  
      return nil
    end
  end
  
  def next_build(current_build)
    all_builds = builds
    index = get_build_index(all_builds, current_build.label)

    if index == (all_builds.size - 1)
      return nil
    else
      return all_builds[index + 1]
    end
  end
  
  def last_complete_build
    builds.reverse.find { |build| !build.incomplete? }
  end

  def find_build(label)
    # this could be optimized a lot
    builds.find { |build| build.label == label }
  end
    
  def last_complete_build_status
    return "failed" if BuilderStatus.new(self).fatal?
    previously_built? ? last_complete_build.status : 'never_built'
  end
  
  def previously_built?
    not last_complete_build.nil?
  end

  # TODO this and last_builds methods are not Project methods, really - they can be inlined somewhere in the controller layer
  def last_five_builds
    last_builds(5)
  end
  
  def last_builds(n)
    builds.reverse[0..(n-1)]
  end

  def build_if_necessary
    begin
      if build_necessary?(reasons = [])
        remove_build_requested_flag_file if build_requested?
        return build(source_control.latest_revision, reasons)
      else
        return nil
      end
    rescue => e
      unless e.message.include? "No commit found in the repository."
        notify(:build_loop_failed, e) rescue nil
        @build_loop_failed = true
        raise
      end 
    ensure
      notify(:sleeping) unless @build_loop_failed rescue nil
    end
  end

  #todo - test
  def build_necessary?(reasons)
    if builds.empty?
      reasons << "This is the first build"
      true
    else 
      @triggers.any? {|t| t.build_necessary?(reasons) }
    end
  end
  
  def build_requested?
    File.file?(build_requested_flag_file)
  end
  
  def request_build
    if builder_state_and_activity == 'builder_down'
      BuilderStarter.begin_builder(name)
      10.times do
        sleep 1.second.to_i
        break if builder_state_and_activity != 'builder_down' 
      end
    end
    unless build_requested?
      notify :build_requested
      create_build_requested_flag_file
    end
  end
  
  def config_modified?
    if config_tracker.config_modified?
      notify :configuration_modified
      true
    else
      false
    end
  end
  
  def build_if_requested
    if build_requested?
      remove_build_requested_flag_file
      build(source_control.latest_revision, ['Build was manually requested.', source_control.latest_revision.to_s])
    end
  end
  
  def force_build(message = 'Build was forced')
    build(source_control.latest_revision, [message, source_control.latest_revision.to_s])
  end
  
  def update_project_to_revision(build, revision)
    if do_clean_checkout?
      File.open(build.artifact('source_control.log'), 'w') do |f| 
        start = Time.now
        f << "checking out build #{build.label}, this could take a while...\n"
        source_control.clean_checkout(revision, f)
        f << "\ntook #{Time.now - start} seconds"
      end
    else
      source_control.update(revision)
    end
  end
  
  def build(revision = source_control.latest_revision, reasons = [])
    if Configuration.serialize_builds

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
    
    respond_to do |format|
      format.html do
        if request.xhr?
          render_projects_partial(@projects)
        else
          render 'index'
        end
      end
      format.rss { render :action => 'index_rss', :layout => false, :format => :xml }
      format.cctray { render :action => 'index_cctray', :layout => false }
    end
  end

  def create
    scm = SourceControl.create(params[:project][:source_control])
    project = Project.create(params[:project][:name], scm)

    redirect_to getting_started_project_path(project.id)
  end

  def getting_started
    @project = Project.find(params[:id])
    @config_example = File.read( File.join("config", "cruise_config.rb.example") )
  end

  def show
    @project = Project.find(params[:id])
    render :text => "Project #{params[:id].inspect} not found", :status => 404 and return unless @project

    respond_to do |format|
      format.html { redirect_to :controller => "builds", :action => "show", :project => @project }
      format.rss { render :action => 'show_rss', :layout => false }
    end
  end

  def build
    render :text => 'Build requests are not allowed', :status => 403 and return if Configuration.disable_build_now

    @project = Project.find(params[:id])
    render :text => "Project #{params[:id].inspect} not found", :status => 404 and return unless @project

    @project.request_build rescue nil

    respond_to do |format| 
      format.html do
        if request.xhr?
          render_projects_partial(Project.all)
        else
          redirect_to :controller => "builds", :action => "show", :project => @project
        end
      end
    end
  end
  
  def code
    if Configuration.disable_code_browsing
      render :text => "Code browsing disabled" and return
    end

    @project = Project.find(params[:id])
    render :text => "Project #{params[:id].inspect} not found", :status => 404 and return unless @project 

    path = File.join(@project.path, 'work', params[:path])
    @line = params[:line].to_i if params[:line]

    if File.directory?(path)
      render :text => 'Viewing of source directories is not supported yet', :status => 500 
    elsif File.file?(path)
      @content = File.read(path)
    else
      render_not_found
    end
  end


  private

    def render_projects_partial(projects)
      if projects.empty?
        render :partial => 'no_projects'
      else
        render :partial => 'project', :collection => projects
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def rss_title(project, build)
    project.name + (build ? " build #{build.abbreviated_label} #{build.status}" :
                            " has never been built")
  end

  def rss_description(project, build)
    build ? build.changeset : ''
  end

  def rss_pub_date(build)
    format_time(build ? build.time : Time.at(0), :rss)
  end

  def rss_link(project, build)
    build ? build_url(:only_path => false, :project => project, :build => build) :
            project_without_builds_url(:only_path => false, :project => project)            
  end

  def show_revisions_in_build(revisions)
    return '' if revisions.empty?    
    if revisions.length == 1
      revision = revisions[0]
      text = "<div><span class='build_author'>#{revision.author}</span>" + ' committed the checkin</div>'
      # TODO: <br/> - should probably use css instead.
      text += '<br/>'
      text +="<div>Comments:<br/>#{format_changeset_log(revision.message)}</div>" unless revision.message.empty?
      text
    else
      committers = revisions.collect { |rev| rev.author }.uniq
      text = "<div><span class='build_author'>#{committers.join(', ')}</span>" + ' committed the checkin</div>'
    end
  end

  def revisions_in_build(build)    
    changeset = build.changeset
    SourceControl::Subversion::ChangesetLogParser.new.parse_log changeset.split("\n")
  end

  # Re-map our project statuses to match the project statuses recognized
  # by CCTray.Net
  def map_to_cctray_project_status(project_status)
    case project_status.to_s
    when 'success', 'building' then 'Success'
    when 'never_built' then 'Unknown'
    when 'failed' then 'Failure'
    else 'Unknown'
    end
  end

  # Re-map our build activities to match the build activities recognized
  # by CCTray.Net
  def map_to_cctray_activity(builder_state)
    case builder_state.to_s
    when 'checking_for_modifications' then 'CheckingModifications'  
    when 'building' then 'Building'
    when 'sleeping', 'builder_down' then 'Sleeping'
    else 'Unknown'
    end
  end

end

app/views/projects/_no_projects.html.erb
<div id="no_projects_help" class="help">
  <h1>Welcome to CruiseControl.rb!</h1>
  <div style="padding: 1em;">
    <p>
      No projects are currently configured (checked <small><%= h Configuration.projects_root %></small>).
    </p>
    <h3>Adding a new project</h3>
    <p>
      You can add a new project using the web interface <%= link_to "here", new_project_path %>.
    </p>
    <p>
      Alternatively, to add a project using the command line, navigate to the directory where you unpacked this tool, and type:
    </p>
    <pre style="font-family: courier, serif">cruise add [project-name] -r [repository] -s [svn|git|hg|bzr]</pre>
    <p>
      If you have a problem with this command, you may find that
      <span style="font-family: courier, serif">cruise help</span> is ... helpful.
      If it isn't, there is always <%= link_to 'the manual', document_path('manual') %> and
      <a href="mailto:cruisecontrolrb-users@rubyforge.org">cruisecontrolrb-users@rubyforge.org</a> mailing list.
    </p>
  </div>
</div>

app/views/projects/_project.html.erb
<div id="project_<%= project.name %>" class="project build_<%= project.last_complete_build_status %>">
<table class="project_pane">
<tr>

  <td class="project_summary">

    <div>
      <span class="project_name">
        <%= link_to project.name, :action => 'show', :id => project.name %>
      </span>
    </div>

    <div class="recent_builds">
      <% recent_builds = project.last_five_builds %>

      <span class="lead">
        <%= recent_builds.first ? 'build ' : '<span class="build_status">Never built</span>'.html_safe %>
        <br/>
        <%= link_to image_tag('rss_light.gif'), :action => 'show', :id => project.name, :format => 'rss' %>
      </span>

      <% unless recent_builds.empty? %>
        <div class="builds_list">
          <% recent_builds.each do |build| %>
            <% if build == recent_builds.first %>
                <div class="build_summary"><%= link_to_build_with_elapsed_time(project, build) %></div>
            <% else %>
                <div class="build_summary"><%= link_to_build(project, build) %></div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </td>

  <td class="builder_control">
    <%= render :partial => "builds/build_buttons", :locals => { :project => project } %>
  </td>

  <td class="build_details">
    <% latest_build = recent_builds.first %>
    <% if latest_build %>
      <% if latest_build.incomplete? %>
        <div>
          Now building: <%= latest_build.abbreviated_label %>
          for <%= format_seconds(latest_build.elapsed_time_in_progress, :general) %>
        </div>
      <% end %>
      <%= show_revisions_in_build(revisions_in_build(latest_build)) %>
      <br />
      <% if latest_build.brief_error %>
        <div><%= link_to latest_build.brief_error, {:action => 'show', :id => project.name}, {:class => "failed"} %></div>
      <% end %>
      <div class="error_message"><%= simple_format(project.builder_error_message) %></div>
    <% end %>   
  </td>
</tr>
</table>
</div>

app/views/projects/_project_brief.html.erb
<tr id="project_<%= project.name %>" class="project build_<%= project.last_complete_build_status %>">
  <td class="project_name"><%= link_to project.name, :action => 'show', :id => project.name %></td>
  <td></td>
  <td></td>
  <td></td>
</tr>

app/views/projects/code.html.erb
<h3><%= File.join(params[:path]) %><span class="help">(latest version)</span></h3>
<div class="code">
<% line_number = 0 %>
<% @content.gsub("  ", " &nbsp;").split("\n").each do |line| %>
  <a name="<%= line_number += 1%>">
    <div class="line<%= @line == line_number ? ' selected_line' : ''%>">
      <span class="line_number"><%= line_number %>:</span><%= line %>
    </div>
  </a>
<% end %>
</div>

app/views/projects/getting_started.html.erb
<h1>Getting started with your new project</h1>

Now that you've created a project, you should use the CCRB API to configure your project. Projects are configured 
using a <code>cruise_config.rb</code> file that gets version-controlled and placed in the root of your project. '
A typical <code>cruise_config.rb</code> file looks like this:

<pre>
<%= @config_example %>
</pre>

To see the builds for your new project, go <%= link_to "here", project_path(@project) %>.

app/views/projects/index.html.erb
<% @rss_feeds = { 'All projects' => {:controller => 'projects', :action => 'index', :format => 'rss'} } -%>
<% @projects.each { |p| @rss_feeds["#{p.name} builds"] = project_url(:controller => 'projects', :action => 'show', :id => p, :format => 'rss')} -%>

<div id="projects" 
  data-refresh-path="<%= projects_path %>" 
  data-refresh-interval="<%= Configuration.dashboard_refresh_interval.to_i * 1000 %>">
  
  <% if @projects.empty? %>
    <%= render :partial => 'no_projects' %>
  <% else %>
    <%= render :partial => 'project', :collection => @projects %>
  <% end %>
</div>

app/views/projects/new.html.erb
<h3>Add a new project using the web interface</h3>
<%= form_for :project, :url => projects_path, :action => :post, :html => { :class => "new_project" } do |p| %>
  <dl>
    <dt><%= p.label :name, "Name:" %></dt>
    <dd><%= p.text_field :name %></dd>

    <%= p.fields_for :source_control do |scm| %>
    <dt><%= scm.label :repository, "Repository path:" %></dt>
    <dd><%= scm.text_field :repository %></dd>

    <dt><%= scm.label :source_control, "Type of source control:" %></dt>
    <dd><%= scm.select :source_control, %w(Git Subversion Mercurial Bazaar) %></dd>
    <% end %>
    <dt><%= content_tag("button", "Create", :type => "submit") %></dt>
    <dd></dd>
  </dl>
<% end %>