config/routes.rb
CruiseControl::Application.routes.draw do
  match '/' => 'projects#index'
  
  resources :projects do  
    member do
      post :build
      get :getting_started
    end
  end

  match 'builds/older/:project' => 'builds#drop_down', :as => :builds_drop_down
  match 'builds/:project/:build/*path' => 'builds#artifact', :as => :build_artifact, :build => /[^\/]+/
  match 'builds/:project/:build' => 'builds#show', :as => :build, :build => /[^\/]+/
  match 'builds/:project' => 'builds#show', :as => :project_without_builds

  match 'projects/code/:id/*path' => 'projects#code', :as => :code

  match 'documentation/plugins' => 'documentation#plugins', :as => :plugin_doc_list
  match 'documentation/plugins/:type/:name' => 'documentation#plugins', :as => :plugin_doc, :name => /[^\/]+/

  match 'documentation/*path' => 'documentation#get', :as => :document
  match 'documentation' => 'documentation#get', :as => :document_root
  
  match 'XmlStatusReport.aspx' => 'projects#index', :format => 'cctray'
  match 'XmlServerReport.aspx' => 'projects#index', :format => 'cctray'

  # TODO Remove this.
  match '/:controller(/:action(/:id))'
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="tw_logo">
    <%= link_to image_tag("tw_open_source.png"), "http://www.thoughtworks.com/" %>
  </div>
  <div class="version">
    <div>Version <%= CruiseControl::VERSION::STRING %></div>
    <div>Powered by <a href="http://rubyonrails.org">Ruby on Rails</a></div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <ul class="main_menu">
    <li class="menu_item">
      <%= link_to_unless_current 'All Projects', projects_path %>
    </li>
    <li class="menu_item">
      <%= link_to_unless_current 'Add Project', new_project_path %>
    </li>
    <li class="menu_item">
      <%= link_to 'Help', document_root_path %>
    </li>
  </ul>

  <div class="cc_logo">
    <%= link_to image_tag("cruise_logo.png"), Configuration.default_page %>
  </div>

  <% unless flash[:notice].blank? -%>
    <div class="flash_notice"><%= h flash[:notice] %></div>
  <% end -%>
</div>

app/views/layouts/application.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>CruiseControl.rb<%= @title ? " - " + @title : '' %></title>
  <%= stylesheet_link_tag 'cruisecontrol', :media => 'all' %>
  <%= stylesheet_link_tag 'site', :media => 'all' if Rails.root.join("public", "stylesheets", "site.css").exist? %>
  

  <% if @autorefresh %>
    <meta http-equiv="refresh" content="5">
    <meta http-equiv="cache-control" content="no-cache">
  <% end %>
  <% if @rss_feeds -%>
    <% @rss_feeds.sort.each do |title, url| -%>
      <%= auto_discovery_link_tag :rss, url_path(url), {:title => title} %>
    <% end -%>
  <% end -%>
  <%= javascript_include_tag "jquery-1.6.1" %>
  <%= javascript_include_tag "application" %>
</head>

<body>

  <%= render :partial => '/layouts/header' %>

  <div id="content">
    <%= yield %>
  </div>

  <%= render :partial => '/layouts/footer' %>

</body>
</html>

app/views/layouts/documentation.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>CruiseControl.rb<%= @title ? " - " + @title : '' %></title>
  <meta name="description" content="Lightweight continuous integration tool" />
  <meta name="keywords"
        content="continuous integration, cruisecontrol, ruby, rails, build, deployment, software, development, agile" />
  <%= stylesheet_link_tag '/thoughtworks_studios/reset', :media => 'all' %>
  <%= stylesheet_link_tag '/thoughtworks_studios/fonts', :media => 'all' %>
  <%= stylesheet_link_tag '/thoughtworks_studios/grids', :media => 'all' %>
  <%= stylesheet_link_tag '/thoughtworks_studios/base', :media => 'all' %>
  <%= stylesheet_link_tag 'documentation', :media => 'all' %>
  <%= javascript_include_tag '/thoughtworks_studios/page' %>
  <%= javascript_include_tag :defaults %>
</head>
<body>
	<div id="doc" class="yui-t4">
    <%= render :partial => '/documentation/header' %>

		<div id="bd" class="thick">
		  <div class="yui-b" id="side-bar">
		    <div class="inner">
          <%= render :partial => '/documentation/' + (@sidebar || 'sidebar_docs') %>
		    </div>
      </div>

		  <div id="yui-main">
		    <div class="yui-b">
		      <div class="inner">
		        <%= yield %>
		      </div>
		    </div>
		  </div>
    </div>

    <%= render :partial => '/documentation/footer' %>
  </div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-9566218-1");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>